version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    steps:
      - checkout

      # Install the AWS CLI
      - run:
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt-get install awscli -y
      - run:
          name: Print working directory
          command: |
                pwd
                cd files/
                ls -al
      # Sync the files to S3
      - run:
          name: Sync files to S3
          command: |
            aws s3 cp files/ s3://gitrepouploadedhere/uploadpartfile --recursive --exclude "*" --include "*.json"

